version: "3.9"
services:

  dab_user_management_svc:
    build:
      context: ./
      dockerfile: prod.Dockerfile
    image: user_management:v0.1.0-beta
    container_name: dab_user_management_svc_prod
    ports:
      - "8001:8001"

  dab_user_management_queue:
    build:
      context: ./
      dockerfile: queue-prod.dockerfile
    image: queue_user_management:v0.1.0-beta
    container_name: dab_user_management_queue_prod
    depends_on:
      - dab_user_management_svc
