version: "3.9"
services:

  dab_user_management_svc:
    build: ./
    image: user_management:v0.1.0-alpha
    container_name: dab_user_management_svc
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  dab_user_management_queue:
    build:
      context: ./
      dockerfile: queue.dockerfile
    image: queue_user_management:v0.1.0-alpha
    container_name: dab_user_management_queue
    volumes:
      - .:/app
    depends_on:
      - dab_user_management_svc
