"""Initial migration

Revision ID: 0d3ded4c0b71
Revises: 
Create Date: 2024-10-03 09:04:06.049109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3ded4c0b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('permission_group_id', sa.Integer(), nullable=True),
    sa.Column('insertedBy', sa.Integer(), nullable=True),
    sa.Column('insertedDate', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_group_id'), 'permission_group', ['id'], unique=False)
    op.create_index(op.f('ix_permission_group_insertedBy'), 'permission_group', ['insertedBy'], unique=False)
    op.create_index(op.f('ix_permission_group_name'), 'permission_group', ['name'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('insertedBy', sa.Integer(), nullable=True),
    sa.Column('insertedDate', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_description'), 'role', ['description'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_insertedBy'), 'role', ['insertedBy'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('role_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('insertedBy', sa.Integer(), nullable=True),
    sa.Column('insertedDate', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_group_id'), 'role_group', ['id'], unique=False)
    op.create_index(op.f('ix_role_group_insertedBy'), 'role_group', ['insertedBy'], unique=False)
    op.create_index(op.f('ix_role_group_name'), 'role_group', ['name'], unique=False)
    op.create_table('role_group_map',
    sa.Column('role_group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_group_id'], ['role_group.id'], ondelete='NO ACTION', use_alter=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='NO ACTION', use_alter=True),
    sa.PrimaryKeyConstraint('role_group_id', 'role_id')
    )
    op.create_index(op.f('ix_role_group_map_role_group_id'), 'role_group_map', ['role_group_id'], unique=False)
    op.create_index(op.f('ix_role_group_map_role_id'), 'role_group_map', ['role_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='NO ACTION', use_alter=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='NO ACTION', use_alter=True),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('lastUpdatedDate', sa.String(length=250), nullable=True),
    sa.Column('lastUpdatedBy', sa.Integer(), nullable=True),
    sa.Column('needsToChangePassword', sa.Boolean(), nullable=True),
    sa.Column('expiryDate', sa.String(length=250), nullable=True),
    sa.Column('contactPhone', sa.String(length=250), nullable=True),
    sa.Column('lastChangedPasswordDate', sa.String(length=250), nullable=True),
    sa.Column('numberOfFailedAttempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_contactPhone'), 'user', ['contactPhone'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_employee_id'), 'user', ['employee_id'], unique=False)
    op.create_index(op.f('ix_user_expiryDate'), 'user', ['expiryDate'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_lastChangedPasswordDate'), 'user', ['lastChangedPasswordDate'], unique=False)
    op.create_index(op.f('ix_user_lastUpdatedBy'), 'user', ['lastUpdatedBy'], unique=False)
    op.create_index(op.f('ix_user_lastUpdatedDate'), 'user', ['lastUpdatedDate'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_needsToChangePassword'), 'user', ['needsToChangePassword'], unique=False)
    op.create_index(op.f('ix_user_numberOfFailedAttempts'), 'user', ['numberOfFailedAttempts'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_table('user_password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('inserted', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password_history_id'), 'user_password_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_password_history_inserted'), 'user_password_history', ['inserted'], unique=False)
    op.create_index(op.f('ix_user_password_history_password'), 'user_password_history', ['password'], unique=False)
    op.create_index(op.f('ix_user_password_history_user_id'), 'user_password_history', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='NO ACTION', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='NO ACTION', use_alter=True),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('insertedBy', sa.Integer(), nullable=False),
    sa.Column('insertedDate', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['permission_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_description'), 'permission', ['description'], unique=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_insertedBy'), 'permission', ['insertedBy'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_insertedBy'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_description'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_password_history_user_id'), table_name='user_password_history')
    op.drop_index(op.f('ix_user_password_history_password'), table_name='user_password_history')
    op.drop_index(op.f('ix_user_password_history_inserted'), table_name='user_password_history')
    op.drop_index(op.f('ix_user_password_history_id'), table_name='user_password_history')
    op.drop_table('user_password_history')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_numberOfFailedAttempts'), table_name='user')
    op.drop_index(op.f('ix_user_needsToChangePassword'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_lastUpdatedDate'), table_name='user')
    op.drop_index(op.f('ix_user_lastUpdatedBy'), table_name='user')
    op.drop_index(op.f('ix_user_lastChangedPasswordDate'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_expiryDate'), table_name='user')
    op.drop_index(op.f('ix_user_employee_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_contactPhone'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_role_group_map_role_id'), table_name='role_group_map')
    op.drop_index(op.f('ix_role_group_map_role_group_id'), table_name='role_group_map')
    op.drop_table('role_group_map')
    op.drop_index(op.f('ix_role_group_name'), table_name='role_group')
    op.drop_index(op.f('ix_role_group_insertedBy'), table_name='role_group')
    op.drop_index(op.f('ix_role_group_id'), table_name='role_group')
    op.drop_table('role_group')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_insertedBy'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_description'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_group_name'), table_name='permission_group')
    op.drop_index(op.f('ix_permission_group_insertedBy'), table_name='permission_group')
    op.drop_index(op.f('ix_permission_group_id'), table_name='permission_group')
    op.drop_table('permission_group')
    # ### end Alembic commands ###
