"""Order added

Revision ID: 9164b7b217a0
Revises: b5280ec06cd7
Create Date: 2024-10-03 10:40:57.945027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9164b7b217a0'
down_revision = 'b5280ec06cd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logged_in_users')
    op.add_column('permission_group', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission_group', 'order')
    op.create_table('logged_in_users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.NVARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
