"""Logged in user table added

Revision ID: 953cbb4cfdb7
Revises: 0d3ded4c0b71
Create Date: 2024-10-03 10:11:25.184413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953cbb4cfdb7'
down_revision = '0d3ded4c0b71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'role_group_map', 'role_group', ['role_group_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    op.create_foreign_key(None, 'role_group_map', 'role', ['role_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    op.create_foreign_key(None, 'user_password_history', 'user', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], ondelete='NO ACTION', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_password_history', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_group_map', type_='foreignkey')
    op.drop_constraint(None, 'role_group_map', type_='foreignkey')
    # ### end Alembic commands ###
