"""Describe changes

Revision ID: b5280ec06cd7
Revises: 953cbb4cfdb7
Create Date: 2024-10-03 10:14:23.853404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5280ec06cd7'
down_revision = '953cbb4cfdb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
