"""Added NewModel table

Revision ID: d41d248fc695
Revises: 9164b7b217a0
Create Date: 2024-10-03 11:57:06.981281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41d248fc695'
down_revision = '9164b7b217a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
